trainers swiper
GSG-G13/gym-react pull request #136
Opened 2023-07-02 20:13 UTC by AhmedMughessib

2023-07-02 21:22 UTC, HamdyPs approved these changes

2023-07-03 11:40 UTC, AdhamHaisami requested changes

2023-07-03 11:40 UTC, AdhamHaisami commented on src/pages/user/home/index.jsx
> +        await handleDataChange(trainers.data.allTrainers);
setState directly. no need for a raper function, and why do you use await in here?

2023-07-03 11:40 UTC, AdhamHaisami commented on src/pages/user/home/index.jsx
> +        const trainers = await axios.get('http://localhost:5050/api/users/trainers');
we don't add the full URL, it's already declared in the vite config file. add only the endpoint

2023-07-03 11:41 UTC, HamdyPs requested changes

2023-07-03 11:41 UTC, HamdyPs commented on src/pages/user/home/index.jsx
> +      try {
u don't need to use try catch, instead u need to check the status that comes from response

2023-07-03 11:41 UTC, HamdyPs commented on src/pages/user/home/index.jsx
> +    const fetchData = async () => {
move this function out of useEffect

2023-07-03 11:42 UTC, HamdyPs requested changes

2023-07-03 11:42 UTC, HamdyPs commented on src/components/swiper/index.jsx
> +          <img height={350} width="300px" style={{ margin: 'auto', borderRadius: 40 }} src={item.image} alt={item} />
change alt value to item.anything from the object

2023-07-10 10:25 UTC, closed without merging