20 sign up form comp
GSG-G13/gym-react pull request #69
Opened 2023-06-22 13:29 UTC by AhmedMughessib

2023-06-24 16:07 UTC, HamdyPs requested changes

2023-06-24 16:07 UTC, HamdyPs commented on src/components/signup/index.jsx
> +const Inputstyled = styled(InputComp)`
here you are extends from a function component, not another style component, change this

2023-06-24 16:07 UTC, HamdyPs commented on src/components/signup/index.jsx
> +const SignupWrapper = styled.div`
move all these style to a sperated file

2023-06-25 12:10 UTC, AdhamHaisami approved these changes

2023-06-25 12:10 UTC, merged